openapi: 3.0.1
info:
  title: 4D GIS 标记系统 API
  description: 4D GIS 标记系统的 API 文档，用于管理具有时间（第4维）和高度的地理空间标记点。
  version: 1.0.0
tags:
  - name: 认证
  - name: 标记点
  - name: 标记类型
paths:
  /auth/register:
    post:
      summary: 用户注册
      deprecated: false
      description: ''
      tags:
        - 认证
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            example: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    example: uuid-user-123
                  message:
                    type: string
                    example: 注册成功
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /auth/login:
    post:
      summary: 用户登录
      deprecated: false
      description: ''
      tags:
        - 认证
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            example:
              identity: '100'
              password: Excepteur enim sed
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          headers: {}
      security: []
  /markers:
    get:
      summary: 获取标记点列表
      deprecated: false
      description: 按时间、高度、类型、关键词、空间范围等条件过滤标记。
      tags:
        - 标记点
      parameters:
        - name: time_start
          in: query
          description: ISO 8601 格式，筛选时间范围开始点。
          required: false
          schema:
            type: string
            format: date-time
        - name: time_end
          in: query
          description: ISO 8601 格式，筛选时间范围结束点。
          required: false
          schema:
            type: string
            format: date-time
        - name: min_height
          in: query
          description: 最小高度（米）
          required: false
          schema:
            type: number
            format: float
        - name: max_height
          in: query
          description: 最大高度（米）
          required: false
          schema:
            type: number
            format: float
        - name: type
          in: query
          description: 标记类型 ID
          required: false
          schema:
            type: string
        - name: keyword
          in: query
          description: 关键词搜索（匹配标题、描述）
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Marker'
          headers: {}
      security: []
    post:
      summary: 创建一个新的 4D 标记点
      deprecated: false
      description: ''
      tags:
        - 标记点
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarkerCreateRequest'
            example: ''
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Marker'
          headers: {}
      security: []
  /markers/{markerId}:
    get:
      summary: 获取单个标记点详情
      deprecated: false
      description: ''
      tags:
        - 标记点
      parameters:
        - name: markerId
          in: path
          description: ''
          required: true
          example: ''
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Marker'
          headers: {}
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
    put:
      summary: 更新一个标记点
      deprecated: false
      description: ''
      tags:
        - 标记点
      parameters:
        - name: markerId
          in: path
          description: ''
          required: true
          example: ''
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema: {}
            example: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Marker'
          headers: {}
      security: []
    delete:
      summary: 删除一个标记点
      deprecated: false
      description: ''
      tags:
        - 标记点
      parameters:
        - name: markerId
          in: path
          description: ''
          required: true
          example: ''
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /marker-types:
    get:
      summary: 获取所有标记类型模板
      deprecated: false
      description: ''
      tags:
        - 标记类型
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MarkerType'
          headers: {}
      security: []
components:
  schemas:
    MarkerUpdateRequest:
      type: object
      properties:
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        altitude:
          type: number
          format: double
        time_start:
          type: string
          format: date-time
          description: 起始时间
        time_end:
          type: string
          format: date-time
          description: 结束时间
        title:
          type: string
          description: 标题
        description:
          type: string
          description: 描述
        typeId:
          type: string
          description: 标记类型的 ID
        visibility:
          type: string
          enum:
            - private
            - public
            - team
          default: private
          description: 标记的可见性
    MarkerCreateRequest:
      type: object
      required:
        - longitude
        - latitude
        - time_start
        - title
        - typeId
      properties:
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        altitude:
          type: number
          format: double
        time_start:
          type: string
          format: date-time
          description: 起始时间
        time_end:
          type: string
          format: date-time
          description: 结束时间
        title:
          type: string
          description: 标题
        description:
          type: string
          description: 描述
        typeId:
          type: string
          description: 标记类型的 ID
        visibility:
          type: string
          enum:
            - private
            - public
            - team
          default: private
          description: 标记的可见性
    Marker:
      type: object
      description: 4D 标记点核心数据模型
      properties:
        id:
          type: string
        longitude:
          type: number
          format: double
          description: 经度
        latitude:
          type: number
          format: double
          description: 纬度
        altitude:
          type: number
          description: 高度
          format: double
        time_start:
          type: string
          format: date-time
          description: 开始时间
        time_end:
          type: string
          format: date-time
          description: 结束时间
        title:
          type: string
          description: 标记标题
        description:
          type: string
          description: 标记描述
        type:
          $ref: '#/components/schemas/MarkerType'
          description: 标记类型
        visibility:
          type: string
          enum:
            - private
            - public
            - team
          description: 标记可见性
        createdBy:
          type: object
          properties:
            userId:
              type: string
            username:
              type: string
          description: 创建者
        createdAt:
          type: string
          format: date-time
          description: 创建时间
        updatedAt:
          type: string
          format: date-time
          description: 更新时间
      required:
        - id
        - longitude
        - latitude
        - time_start
        - title
    MarkerType:
      type: object
      description: 标记类型模板
      properties:
        typeId:
          type: string
        name:
          type: string
        icon:
          type: string
          description: 图标名
        color:
          type: string
          format: hex-color
    RegisterRequest:
      type: object
      required:
        - username
        - email
        - phone
        - password
      properties:
        username:
          type: string
          description: 用户名
        email:
          type: string
          format: email
          description: 邮箱
        phone:
          type: string
          description: 手机号
        password:
          type: string
          format: password
    LoginRequest:
      type: object
      properties:
        identity:
          type: string
          description: 手机号/用户名/邮箱
        password:
          type: string
          format: password
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT Token
        expiresIn:
          type: integer
          description: 过期时间
        user:
          type: object
          properties:
            userId:
              type: string
              description: 用户ID
            username:
              type: string
              description: 用户名
  securitySchemes: {}
servers: []
security: []
